(TeX-add-style-hook
 "preamble"
 (lambda ()
   (TeX-add-to-alist 'LaTeX-provided-package-options
                     '(("geometry" "left=2cm" "right=2cm" "bottom=3cm" "top=2.5cm") ("cleveref" "capitalise") ("algorithm2e" "linesnumbered" "ruled" "vlined") ("xy" "all" "cmtip") ("biblatex" "style=alphabetic")))
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "href")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperimage")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperbaseurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "nolinkurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "url")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "path")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "path")
   (TeX-run-style-hooks
    "geometry"
    "amsmath"
    "amsfonts"
    "amsthm"
    "amssymb"
    "mathtools"
    "soul"
    "xspace"
    "xcolor"
    "enumitem"
    "hyperref"
    "cleveref"
    "booktabs"
    "tabularx"
    "mdframed"
    "multirow"
    "float"
    "algorithm2e"
    "algpseudocode"
    "subcaption"
    "makecell"
    "xy"
    "graphicx"
    "framed"
    "biblatex")
   (TeX-add-symbols
    '("enote" 1)
    '("tr" 1)
    '("algstyle" 1)
    '("abbrsty" 1)
    '("class" 1)
    '("probsty" 1)
    '("vec" 1)
    '("mode" 1)
    '("braket" 2)
    '("ip" 2)
    '("ket" 1)
    '("bra" 1)
    "F"
    "K"
    "Z"
    "R"
    "N"
    "Matrix"
    "Tensor"
    "id"
    "ATF"
    "rk"
    "GI"
    "PK"
    "SK"
    "CFI"
    "ID"
    "QFMI"
    "pGpI"
    "GMW"
    "Alteq"
    "DATFE"
    "MATFE"
    "PATFE"
    "Exp"
    "ATFA"
    "EUFCMA"
    "sEUFCMA"
    "EUFNMA"
    "CROATFE"
    "ROATFE"
    "FS"
    "PI"
    "TIp"
    "DTI"
    "TTI"
    "gainv"
    "gapr"
    "msg"
    "cB"
    "cA"
    "cI"
    "cX"
    "cY"
    "cZ"
    "cK"
    "cP"
    "cS"
    "cD"
    "tA"
    "Tr"
    "sampcost"
    "colcost"
    "invcost"
    "mrkcost"
    "tB"
    "diag"
    "gpmul"
    "gpact"
    "NP"
    "TI"
    "coNP"
    "usecpar"
    "veps"
    "bit"
    "FG"
    "OWA"
    "PRA"
    "PROD"
    "INV"
    "QRO"
    "GLAT"
    "pg"
    "cm"
    "qdm"
    "params"
    "attack"
    "hvsim"
    "dualkey"
    "signlist"
    "PRF"
    "Aut"
    "Adj"
    "lencom"
    "lench"
    "lenr"
    "prep"
    "ids"
    "gaids"
    "kg"
    "dkg"
    "skg"
    "vrfy"
    "unruhsign"
    "gasign"
    "fssign"
    "gafssign"
    "ggm"
    "adj"
    "MEDS"
    "LESS"
    "LCME"
    "CSIFiSh"
    "ComSet"
    "ChaSet"
    "ResSet"
    "com"
    "res"
    "ver"
    "gen"
    "lgen"
    "Igen"
    "ChaSp"
    "rsample"
    "sgn"
    "vrf"
    "pkey"
    "skey"
    "ls"
    "Time"
    "Advantage"
    "O"
    "S")
   (LaTeX-add-environments
    "proof")
   (LaTeX-add-amsthm-newtheorems
    "theorem"
    "lemma"
    "hypothesis"
    "corollary"
    "construction"
    "action"
    "definition"
    "assumption"
    "observation"
    "fact"
    "remark")
   (LaTeX-add-mdframed-mdfdefinestyles
    "figstyle"))
 :latex)

